name: dart_openai
description: Dart SDK for openAI Apis (GPT-4 & DALL-E), integrate easily the power of OpenAI's state-of-the-art AI models into their Dart applications.
version: 5.1.1
homepage: https://github.com/verhouse/openai
repository: https://github.com/verhouse/openai
documentation: https://github.com/verhouse/openai/blob/main/README.md
issue_tracker: https://github.com/verhouse/openai/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  collection: ^1.17.2
  fetch_client: ^1.0.2

dev_dependencies:
  dart_code_metrics: ^4.19.2
  lints: ^3.0.0
  test: ^1.24.3
